languageCode = 'pl-pl'
title = 'Piotr Kosmowski'
theme = 'default'
googleAnalytics = "G-N5X4WQMVC2"

[menus]
    [[menus.after]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 10
#    [[menus.before]]
#        name = 'Docs'
#        pageRef = '/docs'
#        weight = 20
#    [[menus.after]]
#        name = 'Archive'
#        pageRef = '/docs/archive'
#        weight = 20
[params]
    BookTheme = 'auto'
    BookRepo = 'https://github.com/kospiotr/kospiotr.github.io'
    BookEditPath = 'edit/master'
    BookCommitPath = 'commit'
    BookToC = true
    BookDateFormat = '2006-01-02'
[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 3
