siteId: pkosmowski.pl
backend:
  name: github
  repo: kospiotr/kospiotr.github.io
  site_domain: https://pkosmowski.pl
  base_url: https://pkosmowski.pl
  auth_endpoint: /api/auth
media_folder: /static/public
public_folder: /public/
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: posty
    label: Posty
    folder: content/posts/
    create: true
    path: '{{year}}-{{month}}-{{day}}-{{slug}}'
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      - label: Tytuł
        name: title
        widget: string
      - label: Data opublikowania
        name: date
        widget: datetime
        default: "{{now}}"
        format: YYYY-MM-DDTHH:mm:ss
      - label: Szkic
        name: draft
        widget: boolean
        default: false
        hint: Zawartość w trybie szkic nie będzie opublikowana.
      - name: image
        label: Okładka
        widget: image
        required: false
      - label: Treść
        name: body
        widget: markdown
      - label: Tagi
        name: tags
        widget: list
  - name: kursy
    label: Kursy i Szkolenia
    folder: content/kursy
    create: true
    path: '{{slug}}/_index'
    editor:
      preview: false
    fields:
      - label: Tytuł
        name: title
        widget: string
      - label: Szkic
        name: draft
        widget: boolean
        default: false
        hint: Zawartość w trybie szkic nie będzie opublikowana.
      - name: image
        label: Okładka
        widget: image
        required: false
      - label: Treść
        name: body
        widget: markdown
        required: false
      - label: Czas trwania w sumie
        name: total_hours
        widget: string
        required: false
      - label: Uczestnicy
        name: participants
        widget: string
        required: false
      - label: Godzin teoretycznych
        name: theory_hours
        widget: string
        required: false
      - label: Zakres teoretyczny
        name: theory_content
        widget: list
        required: false
        field:
          name: zakres_teoretyczny
          widget: text
      - label: Godzin praktycznych
        name: practice_hours
        widget: string
        required: false
      - label: Zakres praktyczny
        name: practice_content
        widget: list
        required: false
        field:
          name: zakres_praktyczny
          widget: text
      - label: Zielona transformacja
        name: green_transformation
        widget: text
        required: false
      - label: Cyfrowe kompetencje
        name: digital_competences
        widget: text
        required: false
      - label: Kwalifikacje trenerów
        name: trainer_qualifications
        widget: list
        required: false
        field:
          name: kwalifikacja_trenerow
          widget: string