siteId: pkosmowski.pl
backend:
  name: github
  repo: kospiotr/kospiotr.github.io
  site_domain: https://pkosmowski.pl
  base_url: https://pkosmowski.pl
  auth_endpoint: /api/auth
media_folder: /static/public
public_folder: /public/
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: posty
    label: Posty
    folder: content/posts/
    create: true
    path: '{{year}}-{{month}}-{{day}}-{{slug}}'
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        default: "{{now}}"
        format: YYYY-MM-DDTHH:mm:ss
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - name: image
        label: Image
        widget: image
        required: false
      - label: Content
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: notes
    label: Notes
    folder: content/docs/notes
    create: true
    path: '{{slug}}'
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: TOC
        name: toc
        widget: boolean
        default: true
      - name: image
        label: Image
        widget: image
        required: false
      - label: Content
        name: body
        widget: markdown
        required: false